// Year 11 Double Award Questions Data - Edit this file to add or modify questions
const questionsData = [
    { questionNumber: 1, topic: "Electrical Circuits", question: "HT: What happens to resistance in parallel?", answer: "Total resistance is lower than the smallest resistance (1/R = 1/R1 + 1/R2)" },
    { questionNumber: 2, topic: "Electrical Circuits", question: "What is an EMF (electromotive force)?", answer: "The total voltage produced by a power supply" },
    { questionNumber: 3, topic: "Electrical Circuits", question: "What is the difference between EMF and terminal voltage?", answer: "EMF is total voltage, terminal voltage is reduced by internal resistance" },
    { questionNumber: 4, topic: "Electrical Circuits", question: "What is the equation for internal resistance?", answer: "E = V + (I x r), where r is internal resistance" },
    { questionNumber: 5, topic: "Generating Electricity", question: "What is Faraday's law of electromagnetic induction?", answer: "A changing magnetic flux induces an EMF in a conductor" },
    { questionNumber: 6, topic: "Generating Electricity", question: "How does a generator work?", answer: "Coil rotates in a magnetic field, changing magnetic flux induces an EMF" },
    { questionNumber: 7, topic: "Generating Electricity", question: "What is the difference between AC and DC?", answer: "AC alternates direction, DC flows in one direction" },
    { questionNumber: 8, topic: "Generating Electricity", question: "What does a transformer do?", answer: "Changes the voltage of AC electricity" },
    { questionNumber: 9, topic: "Generating Electricity", question: "What is the transformer equation?", answer: "Vs/Vp = Ns/Np = Ip/Is" },
    { questionNumber: 10, topic: "Generating Electricity", question: "How do transformers reduce energy loss in the National Grid?", answer: "Step-up transformers increase voltage (reducing current) which reduces I²R heating losses" },
    { questionNumber: 11, topic: "Energy", question: "What is specific heat capacity?", answer: "Energy needed to raise the temperature of 1 kg of a substance by 1°C" },
    { questionNumber: 12, topic: "Energy", question: "What is the specific heat capacity equation?", answer: "E = m x c x ΔT" },
    { questionNumber: 13, topic: "Energy", question: "What is specific latent heat?", answer: "Energy needed to change the state of 1 kg of a substance (without changing temperature)" },
    { questionNumber: 14, topic: "Energy", question: "What is the specific latent heat equation?", answer: "E = m x L" },
    { questionNumber: 15, topic: "Forces and Motion", question: "What is a scalar quantity?", answer: "Has magnitude only (e.g., speed, distance, mass, energy)" },
    { questionNumber: 16, topic: "Forces and Motion", question: "What is a vector quantity?", answer: "Has magnitude and direction (e.g., velocity, displacement, force, acceleration)" },
    { questionNumber: 17, topic: "Forces and Motion", question: "Define acceleration", answer: "Rate of change of velocity" },
    { questionNumber: 18, topic: "Forces and Motion", question: "What is the equation for acceleration?", answer: "a = (v - u) / t" },
    { questionNumber: 19, topic: "Forces and Motion", question: "What are the 4 SUVAT equations?", answer: "v = u + at; s = ut + 0.5at²; v² = u² + 2as; s = (u + v)t / 2" },
    { questionNumber: 20, topic: "Forces and Motion", question: "What is Newton's first law?", answer: "An object will remain at rest or moving at constant velocity unless acted upon by a force" },
    { questionNumber: 21, topic: "Forces and Motion", question: "What is Newton's second law?", answer: "F = ma (Force equals mass times acceleration)" },
    { questionNumber: 22, topic: "Forces and Motion", question: "What is Newton's third law?", answer: "For every action there is an equal and opposite reaction" },
    { questionNumber: 23, topic: "Forces and Motion", question: "What is momentum?", answer: "p = m x v (mass times velocity)" },
    { questionNumber: 24, topic: "Forces and Motion", question: "What is the principle of conservation of momentum?", answer: "In a closed system, total momentum before = total momentum after" },
    { questionNumber: 25, topic: "Forces and Motion", question: "What is density?", answer: "Mass per unit volume (ρ = m / V)" },
    { questionNumber: 26, topic: "Forces and Motion", question: "What is pressure?", answer: "Force per unit area (P = F / A)" },
    { questionNumber: 27, topic: "Forces and Motion", question: "What is Hooke's law?", answer: "F = kx (Force is proportional to extension)" },
    { questionNumber: 28, topic: "Forces and Motion", question: "What is the elastic limit?", answer: "The maximum stress a material can withstand and still return to original shape" },
    { questionNumber: 29, topic: "Waves", question: "Define wavelength", answer: "Distance between two adjacent points in phase (e.g., crest to crest)" },
    { questionNumber: 30, topic: "Waves", question: "Define frequency", answer: "Number of waves passing a point per second (Hz)" },
    { questionNumber: 31, topic: "Waves", question: "Define amplitude", answer: "Maximum displacement from equilibrium position" },
    { questionNumber: 32, topic: "Waves", question: "What is the wave equation?", answer: "v = f × λ (velocity = frequency × wavelength)" },
    { questionNumber: 33, topic: "Waves", question: "What is the period of a wave?", answer: "Time for one complete oscillation (T = 1 / f)" },
    { questionNumber: 34, topic: "Waves", question: "What is refraction?", answer: "Change in direction of a wave when it moves from one medium to another" },
    { questionNumber: 35, topic: "Waves", question: "What is Snell's law?", answer: "n₁ sin θ₁ = n₂ sin θ₂" },
    { questionNumber: 36, topic: "Waves", question: "What is diffraction?", answer: "Spreading out of waves through a gap or around an obstacle" },
    { questionNumber: 37, topic: "Waves", question: "What is interference?", answer: "Superposition of waves causing constructive or destructive combinations" },
    { questionNumber: 38, topic: "Waves", question: "What is the electromagnetic spectrum in order?", answer: "Radio, Microwave, Infrared, Visible Light, Ultraviolet, X-ray, Gamma" },
    { questionNumber: 39, topic: "Thermal Physics", question: "What is absolute zero in Celsius?", answer: "-273°C or -273.15°C" },
    { questionNumber: 40, topic: "Thermal Physics", question: "How do you convert from Celsius to Kelvin?", answer: "K = °C + 273.15" },
    { questionNumber: 41, topic: "Atomic Physics", question: "What are nucleons?", answer: "Protons and neutrons in the nucleus" },
    { questionNumber: 42, topic: "Atomic Physics", question: "What is the mass number (A)?", answer: "Total number of nucleons (protons + neutrons)" },
    { questionNumber: 43, topic: "Atomic Physics", question: "What is the atomic number (Z)?", answer: "Number of protons" },
    { questionNumber: 44, topic: "Atomic Physics", question: "What are isotopes?", answer: "Atoms of the same element with different numbers of neutrons" },
    { questionNumber: 45, topic: "Atomic Physics", question: "What is radioactive decay?", answer: "Spontaneous breakdown of an unstable nucleus emitting radiation" },
    { questionNumber: 46, topic: "Atomic Physics", question: "What are the 3 types of radioactive decay?", answer: "Alpha (α), Beta (β), Gamma (γ)" },
    { questionNumber: 47, topic: "Atomic Physics", question: "What does an alpha particle consist of?", answer: "2 protons and 2 neutrons (Helium nucleus)" },
    { questionNumber: 48, topic: "Atomic Physics", question: "What is a beta particle?", answer: "A high-energy electron emitted from a nucleus" },
    { questionNumber: 49, topic: "Atomic Physics", question: "What is half-life?", answer: "Time taken for half the nuclei in a radioactive sample to decay" },
    { questionNumber: 50, topic: "Atomic Physics", question: "What is the activity of a radioactive source?", answer: "Number of decays per second (measured in Becquerels, Bq)" },
];
