// Year 10 Questions Data - Edit this file to add or modify questions
const questionsData = [
    { questionNumber: 1, topic: "Electrical Circuits", question: "What is the symbol for a variable resistor?", answer: "Rectangle with diagonal arrow" },
    { questionNumber: 2, topic: "Electrical Circuits", question: "What is the symbol for an LED?", answer: "Circle with triangle and line inside (like a play button) and two small arrows coming off" },
    { questionNumber: 3, topic: "Electrical Circuits", question: "What is the symbol for a thermistor?", answer: "Rectangle with line through (like a hockey stick)" },
    { questionNumber: 4, topic: "Electrical Circuits", question: "What is the symbol for an open switch?", answer: "Two separated circles with a diagonal line from one circle" },
    { questionNumber: 5, topic: "Electrical Circuits", question: "Which type of circuit has components in different loops?", answer: "Parallel" },
    { questionNumber: 6, topic: "Electrical Circuits", question: "What is current?", answer: "Rate of flow of electrons or charge (per second)" },
    { questionNumber: 7, topic: "Electrical Circuits", question: "What is the unit of current?", answer: "A (Amps)" },
    { questionNumber: 8, topic: "Electrical Circuits", question: "How do we measure current?", answer: "With an ammeter in series" },
    { questionNumber: 9, topic: "Electrical Circuits", question: "What is voltage?", answer: "Difference in electrical energy between two points" },
    { questionNumber: 10, topic: "Electrical Circuits", question: "What is the unit of voltage?", answer: "V (Volts)" },
    { questionNumber: 11, topic: "Electrical Circuits", question: "How do we measure voltage?", answer: "With a voltmeter in parallel" },
    { questionNumber: 12, topic: "Electrical Circuits", question: "What happens to current in a series circuit?", answer: "Stays the same everywhere" },
    { questionNumber: 13, topic: "Electrical Circuits", question: "What happens to current in a parallel circuit?", answer: "Splits or shared between loops" },
    { questionNumber: 14, topic: "Electrical Circuits", question: "What happens to voltage in a series circuit?", answer: "Splits or shared between components" },
    { questionNumber: 15, topic: "Electrical Circuits", question: "What happens to voltage in a parallel circuit?", answer: "Stays the same everywhere" },
    { questionNumber: 16, topic: "Electrical Circuits", question: "What is a measure of how difficult it is for current to flow?", answer: "Resistance" },
    { questionNumber: 17, topic: "Electrical Circuits", question: "What is the unit of resistance?", answer: "Ω (Ohms)" },
    { questionNumber: 18, topic: "Electrical Circuits", question: "What equation links voltage, current and resistance?", answer: "Current = Voltage / Resistance (I = V / R)" },
    { questionNumber: 19, topic: "Electrical Circuits", question: "What happens to resistance in series?", answer: "Adds up so total resistance is bigger (R = R1 + R2)" },
    { questionNumber: 20, topic: "Electrical Circuits", question: "Draw the current voltage graph for a resistor at constant temperature", answer: "Straight diagonal line (directly proportional)" },
    { questionNumber: 21, topic: "Electrical Circuits", question: "Draw the current voltage graph for a filament lamp", answer: "Curve (as voltage increases current increases at a decreasing rate)" },
    { questionNumber: 22, topic: "Electrical Circuits", question: "Draw the current voltage graph for a diode", answer: "Flat horizontal line and then sharp rise" },
    { questionNumber: 23, topic: "Electrical Circuits", question: "What is power?", answer: "How much energy is transferred per second" },
    { questionNumber: 24, topic: "Electrical Circuits", question: "What equation links voltage, current and power?", answer: "P = I x V" },
    { questionNumber: 25, topic: "Electrical Circuits", question: "As light intensity increases what happens to the resistance of an LDR?", answer: "Decreases at a decreasing rate" },
    { questionNumber: 26, topic: "Electrical Circuits", question: "What are LDRs used for in the UK?", answer: "Streetlights" },
    { questionNumber: 27, topic: "Electrical Circuits", question: "As temperature increases what happens to the resistance of an ntc thermistor?", answer: "Decreases at a decreasing rate" },
    { questionNumber: 28, topic: "Electrical Circuits", question: "What are ntc thermistors used for in the UK?", answer: "Fire alarms" },
    { questionNumber: 29, topic: "Generating Electricity", question: "What does renewable mean?", answer: "Will not run out and will quickly replenish" },
    { questionNumber: 30, topic: "Generating Electricity", question: "Name 4 non renewable energy sources", answer: "Coal, Oil, Gas, Nuclear" },
    { questionNumber: 31, topic: "Generating Electricity", question: "Name 4 renewable energy sources", answer: "Solar, Wind, Hydroelectric, Wave, Biomass, Geothermal, Tidal" },
    { questionNumber: 32, topic: "Generating Electricity", question: "Which power station uses hot rocks underground to heat water?", answer: "Geothermal" },
    { questionNumber: 33, topic: "Generating Electricity", question: "What does to commission mean?", answer: "Set up and build" },
    { questionNumber: 34, topic: "Generating Electricity", question: "Give an advantage of Nuclear power stations", answer: "No CO2 produced, very efficient, lots of electricity, small amount of fuel, reliable" },
    { questionNumber: 35, topic: "Generating Electricity", question: "Give a disadvantage of Nuclear power stations", answer: "Produces radioactive waste, expensive to commission and decommission" },
    { questionNumber: 36, topic: "Generating Electricity", question: "Give an advantage of Wind power stations", answer: "No fuel cost, No CO2 produced, Cheap to run" },
    { questionNumber: 37, topic: "Generating Electricity", question: "Give a disadvantage of Wind power stations", answer: "Unreliable, don't produce much electricity, ugly" },
    { questionNumber: 38, topic: "Generating Electricity", question: "Give an advantage of Hydroelectric power stations", answer: "No fuel cost, No CO2 produced, Quick start up time, lots of electricity" },
    { questionNumber: 39, topic: "Generating Electricity", question: "Give a disadvantage of Hydroelectric power stations", answer: "Destroy habitats, harm wildlife, large area of land needed" },
    { questionNumber: 40, topic: "Generating Electricity", question: "How is a Biomass power station 'carbon neutral'?", answer: "Plants take in carbon dioxide as they grow and release the same carbon dioxide when burned, this recycles the CO2" },
    { questionNumber: 41, topic: "Energy", question: "What are the 8 different types/forms of energy?", answer: "Heat, Elastic, Chemical, Kinetic, Light, Electrical, Gravitational Potential, Sound" },
    { questionNumber: 42, topic: "Energy", question: "Give 2 examples of things that have chemical energy", answer: "Battery, Food, Fuel, Petrol" },
    { questionNumber: 43, topic: "Energy", question: "What is the law of conservation of energy?", answer: "Energy cannot be created or destroyed, only transferred between stores or transformed between forms" },
    { questionNumber: 44, topic: "Energy", question: "What is efficiency?", answer: "Useful energy out / Total energy in (or as a percentage)" },
    { questionNumber: 45, topic: "Thermal Physics", question: "What is temperature?", answer: "Average kinetic energy of particles (in degrees Celsius or Kelvin)" },
    { questionNumber: 46, topic: "Thermal Physics", question: "What is heat?", answer: "Transfer of thermal energy from a warmer object to a cooler object" },
    { questionNumber: 47, topic: "Thermal Physics", question: "Name 3 ways heat can be transferred", answer: "Conduction, Convection, Radiation" },
    { questionNumber: 48, topic: "Thermal Physics", question: "How does conduction work?", answer: "Vibrating particles transfer energy to neighbouring particles" },
    { questionNumber: 49, topic: "Thermal Physics", question: "How does convection work?", answer: "Particles move in currents, hot particles are less dense and rise, cold particles are denser and sink" },
    { questionNumber: 50, topic: "Thermal Physics", question: "How does radiation work?", answer: "Electromagnetic waves transfer heat without needing a medium" },
];
