// Year 11 Triple Award Questions Data - Edit this file to add or modify questions
const questionsData = [
    { questionNumber: 1, topic: "Further Electrical", question: "What is the peak voltage related to RMS voltage?", answer: "Peak voltage = RMS voltage × √2" },
    { questionNumber: 2, topic: "Further Electrical", question: "What is the equation for power in AC circuits?", answer: "P = V × I × cos φ (where cos φ is the power factor)" },
    { questionNumber: 3, topic: "Further Electrical", question: "What is reactance?", answer: "Opposition to current flow in AC circuits due to capacitors or inductors" },
    { questionNumber: 4, topic: "Further Electrical", question: "What is impedance?", answer: "Total opposition to current flow in AC circuits (includes resistance and reactance)" },
    { questionNumber: 5, topic: "Further Electrical", question: "What is resonance in AC circuits?", answer: "When inductive and capacitive reactances are equal, XL = XC" },
    { questionNumber: 6, topic: "Further Motion", question: "What is work done?", answer: "Energy transferred by a force (W = F × d × cos θ)" },
    { questionNumber: 7, topic: "Further Motion", question: "What is power?", answer: "Rate of doing work (P = W / t or P = F × v)" },
    { questionNumber: 8, topic: "Further Motion", question: "What is the work-energy theorem?", answer: "Work done equals change in kinetic energy (W = ΔEk)" },
    { questionNumber: 9, topic: "Further Motion", question: "What is gravitational potential energy?", answer: "Ep = m × g × h" },
    { questionNumber: 10, topic: "Further Motion", question: "What is elastic potential energy?", answer: "Ep = 0.5 × k × x²" },
    { questionNumber: 11, topic: "Further Motion", question: "What is kinetic energy?", answer: "Ek = 0.5 × m × v²" },
    { questionNumber: 12, topic: "Further Motion", question: "Define torque (moment of a force)?", answer: "Turning effect of a force (τ = F × d, where d is perpendicular distance)" },
    { questionNumber: 13, topic: "Further Motion", question: "What is the principle of moments?", answer: "For equilibrium, clockwise moments = anticlockwise moments" },
    { questionNumber: 14, topic: "Further Motion", question: "What is the center of mass?", answer: "Point where the entire mass of an object can be assumed to act" },
    { questionNumber: 15, topic: "Further Motion", question: "What is angular velocity?", answer: "ω = 2πf = 2π / T (radians per second)" },
    { questionNumber: 16, topic: "Further Motion", question: "What is centripetal acceleration?", answer: "a = v² / r = ω² × r (acceleration towards center of circular motion)" },
    { questionNumber: 17, topic: "Further Motion", question: "What is centripetal force?", answer: "F = m × v² / r = m × ω² × r (force towards center of circular motion)" },
    { questionNumber: 18, topic: "Further Motion", question: "What are the conditions for simple harmonic motion?", answer: "Acceleration is proportional to displacement and in opposite direction: a = -ω² x" },
    { questionNumber: 19, topic: "Further Motion", question: "What is the period of a mass-spring system?", answer: "T = 2π√(m / k)" },
    { questionNumber: 20, topic: "Further Motion", question: "What is the period of a simple pendulum?", answer: "T = 2π√(L / g)" },
    { questionNumber: 21, topic: "Further Waves", question: "What is polarization of waves?", answer: "Process of restricting wave oscillations to one plane" },
    { questionNumber: 22, topic: "Further Waves", question: "What does Malus's law state?", answer: "I = I₀ cos² θ (intensity of polarized light through polarizer)" },
    { questionNumber: 23, topic: "Further Waves", question: "What is coherence in waves?", answer: "Two wave sources have constant phase difference" },
    { questionNumber: 24, topic: "Further Waves", question: "What is the Young's double slit equation?", answer: "λ = ax / D (where a is slit separation, D is distance to screen, x is fringe spacing)" },
    { questionNumber: 25, topic: "Further Waves", question: "What is the single slit diffraction equation?", answer: "b sin θ = λ (where b is slit width, θ is angle to first minimum)" },
    { questionNumber: 26, topic: "Further Waves", question: "What is the diffraction grating equation?", answer: "d sin θ = nλ (where d is grating spacing, n is order number)" },
    { questionNumber: 27, topic: "Further Waves", question: "What does Bragg's law state?", answer: "nλ = 2d sin θ (for X-ray diffraction from crystal planes)" },
    { questionNumber: 28, topic: "Further Waves", question: "What is the Doppler effect?", answer: "Apparent change in frequency of a wave when source or observer moves" },
    { questionNumber: 29, topic: "Further Waves", question: "What is the observed frequency formula for Doppler effect?", answer: "f' = f × (v ± vo) / (v ∓ vs)" },
    { questionNumber: 30, topic: "Further Waves", question: "What is the photoelectric effect?", answer: "Emission of electrons from a surface when light shines on it" },
    { questionNumber: 31, topic: "Further Waves", question: "What is the photoelectric equation?", answer: "E = hf = Φ + KEmax (where Φ is work function)" },
    { questionNumber: 32, topic: "Further Waves", question: "What is the threshold frequency?", answer: "Minimum frequency of light needed to cause photoelectric emission: f₀ = Φ / h" },
    { questionNumber: 33, topic: "Further Thermal", question: "What is the first law of thermodynamics?", answer: "ΔU = Q - W (Change in internal energy = heat added - work done)" },
    { questionNumber: 34, topic: "Further Thermal", question: "What is the second law of thermodynamics?", answer: "Entropy of a closed system always increases" },
    { questionNumber: 35, topic: "Further Thermal", question: "What is the ideal gas law?", answer: "PV = nRT (where n is number of moles, R is gas constant)" },
    { questionNumber: 36, topic: "Further Thermal", question: "What is kinetic theory of gases?", answer: "Relates macroscopic properties to microscopic molecular motion" },
    { questionNumber: 37, topic: "Further Thermal", question: "What is pressure in kinetic theory?", answer: "P = (1/3) × ρ × c² (where ρ is density, c is mean square speed)" },
    { questionNumber: 38, topic: "Further Thermal", question: "What is mean kinetic energy in terms of temperature?", answer: "Ek = (3/2) × k × T (where k is Boltzmann constant)" },
    { questionNumber: 39, topic: "Further Nuclear", question: "What is the mass defect?", answer: "Difference between total mass of nucleons and actual nuclear mass" },
    { questionNumber: 40, topic: "Further Nuclear", question: "What is binding energy?", answer: "Energy released when nucleons combine to form a nucleus: E = Δm × c²" },
    { questionNumber: 41, topic: "Further Nuclear", question: "What is nuclear fission?", answer: "Splitting of heavy nucleus into lighter nuclei, releasing energy" },
    { questionNumber: 42, topic: "Further Nuclear", question: "What is nuclear fusion?", answer: "Combining of light nuclei to form heavier nucleus, releasing energy" },
    { questionNumber: 43, topic: "Further Nuclear", question: "What is the decay constant (λ)?", answer: "Probability that a nucleus will decay per unit time" },
    { questionNumber: 44, topic: "Further Nuclear", question: "What is the activity decay equation?", answer: "A = λN (Activity = decay constant × number of nuclei)" },
    { questionNumber: 45, topic: "Further Nuclear", question: "What is the Geiger-Marsden experiment?", answer: "Alpha particle scattering experiment that revealed the nuclear structure of atoms" },
    { questionNumber: 46, topic: "Further Fields", question: "What is gravitational field strength?", answer: "Gravitational force per unit mass (g = F / m)" },
    { questionNumber: 47, topic: "Further Fields", question: "What is Newton's law of universal gravitation?", answer: "F = G × M × m / r² (where G is gravitational constant)" },
    { questionNumber: 48, topic: "Further Fields", question: "What is orbital speed?", answer: "v = √(GM / r) for circular orbits" },
    { questionNumber: 49, topic: "Further Fields", question: "What is Kepler's third law?", answer: "T² ∝ r³ (orbital period squared is proportional to radius cubed)" },
    { questionNumber: 50, topic: "Further Fields", question: "What is gravitational potential?", answer: "Gravitational potential energy per unit mass: Φ = -GM / r" },
];
